[workspace]
members = [
    "aoc2019",
    "intcode",
    "example-day",
    "day1-1",
    "day1-2",
    "day2-1",
    "day2-2",
    "day3-1",
    "day3-2",
    "day5-1",
    "day5-2",
    "day6-1",
    "day6-2",
    "day7-1",
    "day7-2",
    "day9-1",
    "day9-2",
]

